import { CliError } from "./errors.mjs";

export const MODEL_MARKER = "Generated by @oovz/sew; model configuration only.";
export const MODEL_EDIT_HOSTS = new Set(["codex", "opencode", "gemini-cli"]);
export const ROLES = Object.freeze(["researcher", "engineer", "verifier", "worker"]);
const SLOTS = Object.freeze(["inherit", "balanced", "worker"]);
export const PRESETS = Object.freeze({
  inherit: Object.freeze({ researcher: "inherit", engineer: "inherit", verifier: "inherit", worker: "inherit" }),
  "two-model": Object.freeze({ researcher: "worker", engineer: "worker", verifier: "inherit", worker: "worker" }),
  "three-model": Object.freeze({ researcher: "balanced", engineer: "balanced", verifier: "inherit", worker: "worker" }),
});

export function validateScalar(value, label) {
  if (value === undefined) return undefined;
  const normalized = String(value).trim();
  if (!normalized || /[\r\n\u0000-\u001f\u007f]/u.test(normalized)) {
    throw new CliError(`${label} must be a non-empty single-line value.`);
  }
  return normalized;
}

export function normalizePreset(value) {
  if (!value) throw new CliError("models configure requires --preset inherit, two-model, or three-model.");
  if (!Object.hasOwn(PRESETS, value)) throw new CliError(`Unsupported preset: ${value}`);
  return value;
}

export function parseRoleMap(value, base) {
  const mapping = { ...base };
  if (!value) return mapping;
  for (const assignment of value.split(",")) {
    const parts = assignment.split("=");
    if (parts.length !== 2) throw new CliError(`Invalid --map assignment: ${assignment}`);
    const role = parts[0].trim();
    const slot = parts[1].trim();
    if (!ROLES.includes(role)) throw new CliError(`Unknown role in --map: ${role}`);
    if (!SLOTS.includes(slot)) throw new CliError(`Unknown slot in --map: ${slot}`);
    mapping[role] = slot;
  }
  return mapping;
}

export function modelExtension(host) {
  return host === "codex" ? ".toml" : ".md";
}

export function slotConfiguration(slot, options) {
  if (slot === "inherit") return {};
  const prefix = slot === "worker" ? "worker" : "balanced";
  return {
    model: validateScalar(options[`${prefix}-model`], `--${prefix}-model`),
    thinking: validateScalar(options[`${prefix}-thinking`], `--${prefix}-thinking`),
  };
}

export function validateModelConfiguration(host, preset, mapping, options) {
  if (!MODEL_EDIT_HOSTS.has(host)) {
    throw new CliError(`Model configuration is not supported for ${host}; canonical roles already use the host's inheritance behavior.`);
  }
  if (preset === "inherit") {
    for (const key of ["worker-model", "worker-thinking", "balanced-model", "balanced-thinking", "map"]) {
      if (options[key] !== undefined) throw new CliError(`--${key} is not valid with --preset inherit.`);
    }
    return;
  }
  const used = new Set(Object.values(mapping));
  for (const slot of ["worker", "balanced"]) {
    const model = validateScalar(options[`${slot}-model`], `--${slot}-model`);
    const thinking = validateScalar(options[`${slot}-thinking`], `--${slot}-thinking`);
    if (thinking && !model) throw new CliError(`--${slot}-thinking requires --${slot}-model.`);
    if (used.has(slot) && !model) throw new CliError(`The ${slot} slot is used but --${slot}-model was not provided.`);
    if (!used.has(slot) && (model || thinking)) throw new CliError(`The ${slot} slot is not used by this mapping.`);
    if (host === "opencode" && model && !model.includes("/")) throw new CliError(`OpenCode model IDs must use provider/model syntax: ${model}`);
    if (host === "gemini-cli" && thinking) throw new CliError(`${host} agent files do not expose a supported thinking-level field; omit --${slot}-thinking.`);
  }
}

export function validateStoredModels(models, host) {
  if (models === undefined) return;
  if (!MODEL_EDIT_HOSTS.has(host)) throw new CliError(`Install state contains model configuration for unsupported host ${host}.`, 1);
  if (!models || typeof models !== "object" || Array.isArray(models) || Object.keys(models).length === 0) {
    throw new CliError("The installation state has invalid model configuration.", 1);
  }
  for (const [role, config] of Object.entries(models)) {
    if (!ROLES.includes(role)) throw new CliError(`The installation state contains an unknown model role: ${role}.`, 1);
    if (!config || typeof config !== "object" || Array.isArray(config)) throw new CliError(`The installation state contains invalid model configuration for ${role}.`, 1);
    const keys = Object.keys(config);
    if (keys.some((key) => !["model", "thinking"].includes(key))) throw new CliError(`The installation state contains an unknown model field for ${role}.`, 1);
    let model;
    let thinking;
    try {
      model = validateScalar(config.model, `installation model for ${role}`);
      thinking = validateScalar(config.thinking, `installation thinking value for ${role}`);
    } catch (error) {
      if (error instanceof CliError) throw new CliError(error.message, 1);
      throw error;
    }
    if (!model) throw new CliError(`The installation state model for ${role} is missing.`, 1);
    if (host === "opencode" && !model.includes("/")) throw new CliError(`The installation state OpenCode model for ${role} must use provider/model syntax.`, 1);
    if (host === "gemini-cli" && thinking) throw new CliError(`The installation state contains an unsupported Gemini CLI thinking value for ${role}.`, 1);
  }
}

export function isManagedModelContent(content) {
  return String(content).includes(MODEL_MARKER);
}

function yamlScalar(value) { return JSON.stringify(String(value)); }
function tomlScalar(value) { return JSON.stringify(String(value)); }
function escapeRegex(value) { return String(value).replace(/[.*+?^${}()|[\]\\]/gu, "\\$&"); }

function modelOverlayLines(host, config) {
  const lines = [];
  if (config.model) lines.push(host === "codex" ? `model = ${tomlScalar(config.model)}` : `model: ${yamlScalar(config.model)}`);
  if (config.thinking) {
    if (host === "codex") lines.push(`model_reasoning_effort = ${tomlScalar(config.thinking)}`);
    else if (host === "opencode") lines.push(`variant: ${yamlScalar(config.thinking)}`);
  }
  return lines;
}

function applyTomlModelOverlay(content, config) {
  const marker = `# ${MODEL_MARKER}`;
  const block = [marker, ...modelOverlayLines("codex", config)].join("\n");
  const pattern = new RegExp(`^${escapeRegex(marker)}\n(?:model = .*\n)?(?:model_reasoning_effort = .*\n)?`, "mu");
  if (!config.model && !config.thinking) return content.replace(pattern, "");
  if (pattern.test(content)) return content.replace(pattern, `${block}\n`);
  const anchor = "developer_instructions = ";
  const index = content.indexOf(anchor);
  if (index < 0) throw new CliError("The installed Codex agent file has no developer_instructions field; unable to insert model configuration.", 1);
  return `${content.slice(0, index)}${block}\n${content.slice(index)}`;
}

function applyMarkdownModelOverlay(host, content, config) {
  if (!String(content).startsWith("---\n")) throw new CliError(`The installed ${host} agent file has no YAML frontmatter; unable to configure its model.`, 1);
  const close = content.indexOf("\n---\n", 4);
  if (close < 0) throw new CliError(`The installed ${host} agent file has unterminated YAML frontmatter; unable to configure its model.`, 1);
  const frontmatter = content.slice(4, close);
  const after = content.slice(close + 5);
  const marker = `<!-- ${MODEL_MARKER} -->`;
  const key = (line) => line.match(/^([A-Za-z][A-Za-z0-9_-]*):/u)?.[1];
  const without = (name, lines) => lines.filter((line) => key(line) !== name);
  const upsert = (name, value, lines) => {
    const next = [];
    let inserted = false;
    for (const line of lines) {
      if (!inserted && line.startsWith("description:")) {
        next.push(line, `${name}: ${value}`);
        inserted = true;
      } else if (key(line) !== name) {
        next.push(line);
      }
    }
    if (!inserted) next.push(`${name}: ${value}`);
    return next;
  };
  const lines = frontmatter.split("\n").filter(Boolean);
  let nextLines;
  if (!config.model && !config.thinking) {
    nextLines = without("model", without("variant", lines));
    if (host === "gemini-cli") nextLines.push("model: inherit");
  } else {
    nextLines = upsert("model", yamlScalar(config.model), without("variant", lines));
    if (host === "opencode" && config.thinking) nextLines = upsert("variant", yamlScalar(config.thinking), nextLines);
  }
  const nextAfter = after.startsWith(`${marker}\n`) ? after.slice(marker.length + 1) : after;
  const markerLine = config.model || config.thinking ? `${marker}\n` : "";
  return `---\n${nextLines.join("\n")}\n---\n${markerLine}${nextAfter}`;
}

export function applyModelOverlay(host, content, config) {
  if (host === "codex") return applyTomlModelOverlay(content, config);
  if (host === "opencode" || host === "gemini-cli") return applyMarkdownModelOverlay(host, content, config);
  throw new CliError(`${host} does not support in-place model configuration.`, 1);
}
