import { randomUUID } from "node:crypto";
import { lstat, mkdir, readFile, readdir, rename, rm, unlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const PACKAGE_NAME = "@oovz/sew-models";
const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_MANIFEST = JSON.parse(await readFile(path.join(PACKAGE_ROOT, "package.json"), "utf8"));
const PACKAGE_VERSION = PACKAGE_MANIFEST.version;
const MARKER = `Generated by ${PACKAGE_NAME}; model configuration only.`;
const TEMPLATE_ROOT = path.join(PACKAGE_ROOT, "templates");

const HOSTS = ["claude-code", "codex", "opencode"];
const ROLES = ["researcher", "engineer", "verifier", "worker"];
const SLOTS = ["inherit", "balanced", "worker"];
const PRESETS = Object.freeze({
  inherit: Object.freeze({ researcher: "inherit", engineer: "inherit", verifier: "inherit", worker: "inherit" }),
  "two-model": Object.freeze({ researcher: "worker", engineer: "worker", verifier: "inherit", worker: "worker" }),
  "three-model": Object.freeze({ researcher: "balanced", engineer: "balanced", verifier: "inherit", worker: "worker" }),
});
const PRESET_ALIASES = Object.freeze({ cost: "two-model", balanced: "three-model" });
const ROLE_LABELS = Object.freeze({
  researcher: "Researcher",
  engineer: "Engineer",
  verifier: "Verifier",
  worker: "Worker",
});

const COMMAND_OPTIONS = Object.freeze({
  configure: Object.freeze({
    values: new Set([
      "host",
      "scope",
      "project",
      "preset",
      "worker-model",
      "worker-thinking",
      "balanced-model",
      "balanced-thinking",
      "map",
    ]),
    booleans: new Set(["dry-run", "force", "json", "help"]),
  }),
  doctor: Object.freeze({
    values: new Set(["host", "project"]),
    booleans: new Set(["json", "help"]),
  }),
});

class CliError extends Error {
  constructor(message, exitCode = 2) {
    super(message);
    this.name = "CliError";
    this.exitCode = exitCode;
  }
}

function usage() {
  return `${PACKAGE_NAME} ${PACKAGE_VERSION}

Configure Senior Engineering Workflow subagent model and thinking settings.

Usage:
  sew-models configure --host <claude-code|codex|opencode> --preset <inherit|two-model|three-model> [options]
  sew-models doctor [--host <all|claude-code|codex|opencode>] [options]

Configure options:
  --scope <user|project>          Target scope (default: user)
  --project <path>               Project root (default: current directory)
  --worker-model <id>            Model for the worker slot
  --worker-thinking <value>      Host-native thinking/effort/variant value
  --balanced-model <id>          Model for the balanced slot
  --balanced-thinking <value>    Host-native thinking/effort/variant value
  --map <role=slot,...>          Slots: inherit, balanced, worker
  --dry-run                      Show changes without writing
  --force                        Replace an unmanaged sew-* alias file
  --json                         Emit JSON

Doctor options:
  --host <all|list>              Inspect all hosts by default; comma lists are accepted
  --project <path>               Project root (default: current directory)
  --json                         Emit JSON

Notes:
  configure --preset inherit removes only files marked as generated by ${PACKAGE_NAME}.
  doctor is read-only and never invokes a coding-agent binary or a model API.
`;
}

function parseArgs(argv) {
  const args = [...argv];
  const first = args[0];
  if (first === "--help" || first === "-h") return { command: "help", options: {} };
  if (first === "--version" || first === "-v") return { command: "version", options: {} };
  const command = args.shift() ?? "help";
  const definition = COMMAND_OPTIONS[command];
  if (!definition) throw new CliError(`Unknown command: ${command}\n\n${usage()}`);

  const options = {};
  while (args.length > 0) {
    const token = args.shift();
    if (!token.startsWith("--")) throw new CliError(`Unexpected positional argument: ${token}`);
    const raw = token.slice(2);
    const equal = raw.indexOf("=");
    const key = equal >= 0 ? raw.slice(0, equal) : raw;
    if (!key) throw new CliError("Empty option name.");
    if (Object.hasOwn(options, key)) throw new CliError(`Option --${key} may be provided only once.`);
    if (!definition.values.has(key) && !definition.booleans.has(key)) {
      throw new CliError(`Unknown option for ${command}: --${key}`);
    }
    if (definition.booleans.has(key)) {
      if (equal >= 0) throw new CliError(`Boolean option --${key} does not accept a value.`);
      options[key] = true;
      continue;
    }
    const value = equal >= 0 ? raw.slice(equal + 1) : args.shift();
    if (value === undefined || value.startsWith("--")) throw new CliError(`Option --${key} requires a value.`);
    if (!value.trim()) throw new CliError(`Option --${key} must not be empty.`);
    options[key] = value;
  }
  return { command, options };
}

function normalizeHost(value) {
  if (!HOSTS.includes(value)) throw new CliError(`--host must be one of: ${HOSTS.join(", ")}`);
  return value;
}

function normalizeDoctorHosts(value = "all") {
  const requested = value === "all" ? HOSTS : value.split(",").map((item) => item.trim()).filter(Boolean);
  if (requested.length === 0) throw new CliError("--host must name at least one host.");
  const unique = [...new Set(requested.map(normalizeHost))];
  return unique;
}

function normalizeScope(value = "user") {
  if (value !== "user" && value !== "project") throw new CliError(`--scope must be user or project, received: ${value}`);
  return value;
}

function normalizePreset(value) {
  if (!value) throw new CliError("configure requires --preset inherit, two-model, or three-model.");
  const normalized = PRESET_ALIASES[value] ?? value;
  if (!Object.hasOwn(PRESETS, normalized)) throw new CliError(`Unsupported preset: ${value}`);
  return normalized;
}

function validateScalar(value, label) {
  if (value === undefined) return undefined;
  const normalized = String(value).trim();
  if (!normalized || /[\r\n\u0000-\u001f\u007f]/u.test(normalized)) {
    throw new CliError(`${label} must be a non-empty single-line value.`);
  }
  return normalized;
}

function parseRoleMap(value, base) {
  const mapping = { ...base };
  if (!value) return mapping;
  for (const assignment of value.split(",")) {
    const parts = assignment.split("=");
    if (parts.length !== 2) throw new CliError(`Invalid --map assignment: ${assignment}`);
    const role = parts[0].trim();
    const slot = parts[1].trim();
    if (!ROLES.includes(role)) throw new CliError(`Unknown role in --map: ${role}`);
    if (!SLOTS.includes(slot)) throw new CliError(`Unknown slot in --map: ${slot}`);
    mapping[role] = slot;
  }
  return mapping;
}

function homeDirectory(env = process.env, platform = process.platform, fallback = os.homedir()) {
  const candidates = platform === "win32"
    ? [env.USERPROFILE, env.HOME, fallback]
    : [env.HOME, fallback, env.USERPROFILE];
  const selected = candidates.find((item) => typeof item === "string" && item.trim());
  if (!selected) throw new CliError("Unable to determine the user home directory.");
  return path.resolve(selected);
}

function userRoot(host, { env = process.env, platform = process.platform, home = homeDirectory(env, platform) } = {}) {
  if (host === "claude-code") return path.resolve(env.CLAUDE_CONFIG_DIR || path.join(home, ".claude"));
  if (host === "codex") return path.resolve(env.CODEX_HOME || path.join(home, ".codex"));
  if (env.OPENCODE_CONFIG_DIR) return path.resolve(env.OPENCODE_CONFIG_DIR);
  const xdg = env.XDG_CONFIG_HOME ? path.resolve(env.XDG_CONFIG_HOME) : path.join(home, ".config");
  return path.join(xdg, "opencode");
}

function projectRootForHost(host, projectRoot) {
  const root = path.resolve(projectRoot);
  if (host === "claude-code") return path.join(root, ".claude");
  if (host === "codex") return path.join(root, ".codex");
  return path.join(root, ".opencode");
}

function resolveTargetRoot({ host, scope, projectRoot, env = process.env, platform = process.platform, home } = {}) {
  return scope === "project"
    ? projectRootForHost(host, projectRoot ?? process.cwd())
    : userRoot(host, { env, platform, home });
}

function extensionForHost(host) {
  return host === "codex" ? ".toml" : ".md";
}

function managedName(role, host) {
  return `sew-${role}${extensionForHost(host)}`;
}

function managedPath(targetRoot, role, host) {
  return path.join(targetRoot, "agents", managedName(role, host));
}

function isContained(root, candidate) {
  const relative = path.relative(path.resolve(root), path.resolve(candidate));
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

async function pathInfo(file) {
  try {
    return await lstat(file);
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

async function assertSafeManagedPath(targetRoot, file) {
  if (!isContained(targetRoot, file)) throw new CliError(`Managed path escapes target root: ${file}`, 1);
  for (const item of [targetRoot, path.join(targetRoot, "agents"), file]) {
    const info = await pathInfo(item);
    if (info?.isSymbolicLink()) throw new CliError(`Refusing a symlink or junction in the managed path: ${item}`, 1);
  }
}

function yamlScalar(value) {
  return JSON.stringify(String(value));
}

function tomlScalar(value) {
  return JSON.stringify(String(value));
}

function tomlMultiline(value) {
  return `'''\n${String(value).replaceAll("'''", "'\\'\\''").replace(/\s+$/u, "")}\n'''`;
}

function stripFrontmatter(markdown) {
  const normalized = String(markdown).replaceAll("\r\n", "\n");
  if (!normalized.startsWith("---\n")) return normalized.trim();
  const end = normalized.indexOf("\n---\n", 4);
  if (end < 0) throw new CliError("Role template has unterminated frontmatter.", 1);
  return normalized.slice(end + 5).trim();
}

async function roleBody(role) {
  return stripFrontmatter(await readFile(path.join(TEMPLATE_ROOT, `${role}.md`), "utf8"));
}

function aliasDescription(role) {
  const label = ROLE_LABELS[role];
  return `Model-configured Senior Engineering Workflow ${label} alias. Use for the ${label} capability when Senior Engineering Workflow is active and this alias is available.`;
}

function slotConfiguration(slot, options) {
  if (slot === "inherit") return { slot, model: undefined, thinking: undefined };
  const prefix = slot === "worker" ? "worker" : "balanced";
  return {
    slot,
    model: validateScalar(options[`${prefix}-model`], `--${prefix}-model`),
    thinking: validateScalar(options[`${prefix}-thinking`], `--${prefix}-thinking`),
  };
}

function validateConfiguration(host, preset, mapping, options) {
  if (preset === "inherit") {
    for (const key of ["worker-model", "worker-thinking", "balanced-model", "balanced-thinking", "map"]) {
      if (options[key] !== undefined) throw new CliError(`--${key} is not valid with --preset inherit.`);
    }
    return;
  }

  const used = new Set(Object.values(mapping));
  for (const slot of ["worker", "balanced"]) {
    const prefix = slot;
    const model = validateScalar(options[`${prefix}-model`], `--${prefix}-model`);
    const thinking = validateScalar(options[`${prefix}-thinking`], `--${prefix}-thinking`);
    if (thinking && !model) throw new CliError(`--${prefix}-thinking requires --${prefix}-model.`);
    if (used.has(slot) && !model) throw new CliError(`The ${slot} slot is used but --${prefix}-model was not provided.`);
    if (!used.has(slot) && (model || thinking)) throw new CliError(`The ${slot} slot is not used by this mapping.`);
    if (host === "opencode" && model && !model.includes("/")) {
      throw new CliError(`OpenCode model IDs must use provider/model syntax: ${model}`);
    }
  }
}

async function renderAlias(host, role, slot, options) {
  const body = await roleBody(role);
  const config = slotConfiguration(slot, options);
  const description = aliasDescription(role);
  if (host === "claude-code") {
    const lines = [
      "---",
      `name: ${yamlScalar(`sew-${role}`)}`,
      `description: ${yamlScalar(description)}`,
      `model: ${yamlScalar(config.model ?? "inherit")}`,
    ];
    if (config.thinking) lines.push(`effort: ${yamlScalar(config.thinking)}`);
    lines.push("---", `<!-- ${MARKER} -->`, "", body, "");
    return lines.join("\n");
  }
  if (host === "codex") {
    const lines = [
      `# ${MARKER}`,
      `name = ${tomlScalar(`sew-${role}`)}`,
      `description = ${tomlScalar(description)}`,
    ];
    if (config.model) lines.push(`model = ${tomlScalar(config.model)}`);
    if (config.thinking) lines.push(`model_reasoning_effort = ${tomlScalar(config.thinking)}`);
    lines.push(`developer_instructions = ${tomlMultiline(body)}`, "");
    return lines.join("\n");
  }
  const lines = [
    "---",
    `description: ${yamlScalar(description)}`,
    "mode: subagent",
  ];
  if (config.model) lines.push(`model: ${yamlScalar(config.model)}`);
  if (config.thinking) lines.push(`variant: ${yamlScalar(config.thinking)}`);
  lines.push("---", `<!-- ${MARKER} -->`, "", body, "");
  return lines.join("\n");
}

function isManagedContent(content) {
  return String(content).includes(MARKER);
}

async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true });
  const temp = path.join(path.dirname(file), `.${path.basename(file)}.${process.pid}.${randomUUID()}.tmp`);
  const backup = path.join(path.dirname(file), `.${path.basename(file)}.${process.pid}.${randomUUID()}.bak`);
  await writeFile(temp, content, { encoding: "utf8", mode: 0o600 });
  try {
    await rename(temp, file);
    return;
  } catch (error) {
    if (!new Set(["EEXIST", "EPERM", "EACCES", "ENOTEMPTY"]).has(error?.code)) {
      await rm(temp, { force: true });
      throw error;
    }
  }

  let movedExisting = false;
  try {
    if (await pathInfo(file)) {
      await rename(file, backup);
      movedExisting = true;
    }
    await rename(temp, file);
    if (movedExisting) await rm(backup, { force: true });
  } catch (error) {
    await rm(temp, { force: true });
    if (movedExisting && !(await pathInfo(file)) && (await pathInfo(backup))) {
      await rename(backup, file);
    }
    throw error;
  } finally {
    await rm(temp, { force: true });
    if (await pathInfo(file)) await rm(backup, { force: true });
  }
}

function printResult(result, json) {
  if (json) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    return;
  }
  if (result.command === "configure") {
    process.stdout.write(`${result.status}: ${result.host}/${result.scope}\n`);
    for (const item of result.files) process.stdout.write(`- ${item.action.padEnd(17)} ${item.path}\n`);
    return;
  }
  process.stdout.write(`Senior Engineering Workflow model doctor: ${result.status}\n`);
  for (const host of result.hosts) {
    process.stdout.write(`\n${host.host}\n`);
    for (const finding of host.findings) process.stdout.write(`- [${finding.level.toUpperCase()}] ${finding.message}\n`);
  }
  process.stdout.write(`\nSummary: ${result.summary.information} information, ${result.summary.warnings} warnings, ${result.summary.errors} errors.\n`);
}

async function configure(options) {
  const host = normalizeHost(options.host);
  const scope = normalizeScope(options.scope);
  const preset = normalizePreset(options.preset);
  const projectRoot = path.resolve(options.project ?? process.cwd());
  const mapping = parseRoleMap(options.map, PRESETS[preset]);
  validateConfiguration(host, preset, mapping, options);
  const targetRoot = resolveTargetRoot({ host, scope, projectRoot });

  const plan = [];
  for (const role of ROLES) {
    const file = managedPath(targetRoot, role, host);
    await assertSafeManagedPath(targetRoot, file);
    const info = await pathInfo(file);
    const current = info ? await readFile(file, "utf8") : null;
    if (preset === "inherit") {
      if (!info) plan.push({ role, path: file, action: "already-absent" });
      else if (isManagedContent(current)) plan.push({ role, path: file, action: "remove" });
      else plan.push({ role, path: file, action: "preserve-unmanaged" });
      continue;
    }

    const content = await renderAlias(host, role, mapping[role], options);
    if (info && !isManagedContent(current) && !options.force) {
      throw new CliError(`Refusing to replace unmanaged alias file ${file}. Use --force only after reviewing it.`, 1);
    }
    plan.push({ role, path: file, action: info ? "update" : "create", content, slot: mapping[role] });
  }

  if (!options["dry-run"]) {
    for (const item of plan) {
      if (item.action === "remove") await unlink(item.path);
      if (item.action === "create" || item.action === "update") await atomicWrite(item.path, item.content);
    }
  }

  const result = {
    command: "configure",
    status: options["dry-run"] ? "dry-run" : "configured",
    host,
    scope,
    preset,
    targetRoot,
    mapping,
    files: plan.map(({ content: _content, ...item }) => item),
  };
  printResult(result, options.json);
  return 0;
}

function unquote(value) {
  const trimmed = String(value).trim();
  if (!trimmed) return "";
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try { return JSON.parse(trimmed); } catch { return trimmed.slice(1, -1); }
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) return trimmed.slice(1, -1).replaceAll("''", "'");
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  return trimmed;
}

function parseFrontmatterScalars(content) {
  const normalized = String(content).replaceAll("\r\n", "\n");
  if (!normalized.startsWith("---\n")) return {};
  const end = normalized.indexOf("\n---\n", 4);
  if (end < 0) throw new Error("unterminated YAML frontmatter");
  const result = {};
  for (const line of normalized.slice(4, end).split("\n")) {
    const match = /^([A-Za-z0-9_-]+):\s*(.*?)\s*$/.exec(line);
    if (match) result[match[1]] = unquote(match[2]);
  }
  return result;
}

function stripTomlComment(line) {
  let quote = null;
  let escaped = false;
  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    if (escaped) { escaped = false; continue; }
    if (quote === '"' && char === "\\") { escaped = true; continue; }
    if (quote) { if (char === quote) quote = null; continue; }
    if (char === '"' || char === "'") { quote = char; continue; }
    if (char === "#") return line.slice(0, i);
  }
  return line;
}

function parseTomlScalars(content) {
  const result = new Map([["", {}]]);
  let section = "";
  for (const rawLine of String(content).replaceAll("\r\n", "\n").split("\n")) {
    const line = stripTomlComment(rawLine).trim();
    if (!line) continue;
    const sectionMatch = /^\[([^\]]+)\]$/.exec(line);
    if (sectionMatch) {
      section = sectionMatch[1].trim();
      if (!result.has(section)) result.set(section, {});
      continue;
    }
    const assignment = /^([A-Za-z0-9_.-]+)\s*=\s*(.+)$/.exec(line);
    if (!assignment) continue;
    const value = assignment[2].trim();
    if (value.startsWith("'''" ) || value.startsWith('"""')) continue;
    result.get(section)[assignment[1]] = unquote(value);
  }
  return result;
}

function stripJsonComments(input) {
  let output = "";
  let inString = false;
  let escaped = false;
  let lineComment = false;
  let blockComment = false;
  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    const next = input[i + 1];
    if (lineComment) {
      if (char === "\n") { lineComment = false; output += char; }
      continue;
    }
    if (blockComment) {
      if (char === "*" && next === "/") { blockComment = false; i += 1; }
      else if (char === "\n") output += "\n";
      continue;
    }
    if (inString) {
      output += char;
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') { inString = true; output += char; continue; }
    if (char === "/" && next === "/") { lineComment = true; i += 1; continue; }
    if (char === "/" && next === "*") { blockComment = true; i += 1; continue; }
    output += char;
  }
  return output;
}

function removeTrailingJsonCommas(input) {
  let output = "";
  let inString = false;
  let escaped = false;
  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    if (inString) {
      output += char;
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') { inString = true; output += char; continue; }
    if (char === ",") {
      let j = i + 1;
      while (j < input.length && /\s/u.test(input[j])) j += 1;
      if (input[j] === "}" || input[j] === "]") continue;
    }
    output += char;
  }
  return output;
}

function parseJsonc(content) {
  return JSON.parse(removeTrailingJsonCommas(stripJsonComments(String(content))));
}

async function listFiles(directory, extension) {
  try {
    const entries = await readdir(directory, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(extension))
      .map((entry) => path.join(directory, entry.name))
      .sort();
  } catch (error) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
}

function finding(level, code, message, details = undefined) {
  return { level, code, message, ...(details === undefined ? {} : { details }) };
}

async function scanMarkdownAgents(directory, scope) {
  const definitions = [];
  const findings = [];
  for (const file of await listFiles(directory, ".md")) {
    try {
      const content = await readFile(file, "utf8");
      const frontmatter = parseFrontmatterScalars(content);
      if (frontmatter.model === undefined && frontmatter.effort === undefined && frontmatter.variant === undefined && !isManagedContent(content)) continue;
      definitions.push({
        scope,
        path: file,
        name: frontmatter.name ?? path.basename(file, ".md"),
        model: frontmatter.model,
        thinking: frontmatter.effort ?? frontmatter.variant,
        generated: isManagedContent(content),
      });
    } catch (error) {
      findings.push(finding("warning", "agent-parse", `Could not parse agent file ${file}: ${error.message}`));
    }
  }
  return { definitions, findings };
}

async function scanCodexAgents(directory, scope) {
  const definitions = [];
  const findings = [];
  for (const file of await listFiles(directory, ".toml")) {
    try {
      const content = await readFile(file, "utf8");
      const root = parseTomlScalars(content).get("") ?? {};
      if (root.model === undefined && root.model_reasoning_effort === undefined && !isManagedContent(content)) continue;
      definitions.push({
        scope,
        path: file,
        name: root.name ?? path.basename(file, ".toml"),
        model: root.model,
        thinking: root.model_reasoning_effort,
        generated: isManagedContent(content),
      });
    } catch (error) {
      findings.push(finding("warning", "agent-parse", `Could not parse agent file ${file}: ${error.message}`));
    }
  }
  return { definitions, findings };
}

function duplicateFindings(definitions) {
  const byName = new Map();
  for (const definition of definitions) {
    const key = String(definition.name).toLowerCase();
    if (!byName.has(key)) byName.set(key, []);
    byName.get(key).push(definition);
  }
  return [...byName.entries()]
    .filter(([, items]) => items.length > 1)
    .map(([name, items]) => finding(
      "warning",
      "duplicate-agent",
      `Multiple model definitions were found for agent ${name}; host precedence determines the effective one.`,
      items.map((item) => ({ scope: item.scope, path: item.path, model: item.model, thinking: item.thinking })),
    ));
}

async function inspectClaude(projectRoot, env) {
  const root = userRoot("claude-code", { env });
  const locations = [
    { scope: "user", root, agents: path.join(root, "agents") },
    { scope: "project", root: path.join(projectRoot, ".claude"), agents: path.join(projectRoot, ".claude", "agents") },
  ];
  const definitions = [];
  const findings = [];
  for (const location of locations) {
    const scan = await scanMarkdownAgents(location.agents, location.scope);
    definitions.push(...scan.definitions);
    findings.push(...scan.findings);
  }
  if (env.CLAUDE_CODE_SUBAGENT_MODEL) {
    findings.push(finding("warning", "claude-model-env", "CLAUDE_CODE_SUBAGENT_MODEL is set and may override agent model frontmatter.", { value: env.CLAUDE_CODE_SUBAGENT_MODEL }));
  }
  if (env.CLAUDE_CODE_EFFORT_LEVEL) {
    findings.push(finding("information", "claude-effort-env", "CLAUDE_CODE_EFFORT_LEVEL is set for the session baseline.", { value: env.CLAUDE_CODE_EFFORT_LEVEL }));
  }
  findings.push(...duplicateFindings(definitions));
  if (definitions.length === 0) findings.push(finding("information", "no-explicit-agents", "No user or project agent model overrides were found."));
  return { host: "claude-code", locations, definitions, settings: [], findings };
}

async function inspectCodexConfig(file, scope) {
  try {
    const sections = parseTomlScalars(await readFile(file, "utf8"));
    const settings = [];
    const agents = sections.get("agents") ?? {};
    if (agents.default_subagent_model !== undefined || agents.default_subagent_reasoning_effort !== undefined) {
      settings.push({
        scope,
        path: file,
        section: "agents",
        defaultSubagentModel: agents.default_subagent_model,
        defaultSubagentThinking: agents.default_subagent_reasoning_effort,
      });
    }
    for (const [section, values] of sections) {
      if (!section.startsWith("agents.")) continue;
      if (values.model === undefined && values.model_reasoning_effort === undefined && values.config_file === undefined) continue;
      settings.push({
        scope,
        path: file,
        section,
        model: values.model,
        thinking: values.model_reasoning_effort,
        configFile: values.config_file,
      });
    }
    return { settings, findings: [] };
  } catch (error) {
    if (error?.code === "ENOENT") return { settings: [], findings: [] };
    return { settings: [], findings: [finding("warning", "config-parse", `Could not parse Codex config ${file}: ${error.message}`)] };
  }
}

async function inspectCodex(projectRoot, env) {
  const user = userRoot("codex", { env });
  const project = path.join(projectRoot, ".codex");
  const locations = [
    { scope: "user", root: user, agents: path.join(user, "agents"), config: path.join(user, "config.toml") },
    { scope: "project", root: project, agents: path.join(project, "agents"), config: path.join(project, "config.toml") },
  ];
  const definitions = [];
  const settings = [];
  const findings = [];
  for (const location of locations) {
    const scan = await scanCodexAgents(location.agents, location.scope);
    definitions.push(...scan.definitions);
    findings.push(...scan.findings);
    const config = await inspectCodexConfig(location.config, location.scope);
    settings.push(...config.settings);
    findings.push(...config.findings);
  }
  findings.push(...duplicateFindings(definitions));
  for (const setting of settings.filter((item) => item.defaultSubagentModel || item.defaultSubagentThinking)) {
    findings.push(finding("warning", "codex-subagent-default", `Codex subagent defaults in ${setting.path} can replace parent model or thinking inheritance.`, setting));
  }
  if (definitions.length === 0 && settings.length === 0) findings.push(finding("information", "no-explicit-agents", "No Codex subagent model overrides or defaults were found."));
  return { host: "codex", locations, definitions, settings, findings };
}

async function inspectOpenCodeConfig(file, scope) {
  try {
    const value = parseJsonc(await readFile(file, "utf8"));
    const agents = value?.agent ?? value?.agents ?? {};
    const settings = [];
    for (const [name, config] of Object.entries(agents)) {
      if (!config || typeof config !== "object") continue;
      if (config.model === undefined && config.variant === undefined) continue;
      settings.push({ scope, path: file, name, model: config.model, thinking: config.variant });
    }
    return { settings, findings: [] };
  } catch (error) {
    if (error?.code === "ENOENT") return { settings: [], findings: [] };
    return { settings: [], findings: [finding("warning", "config-parse", `Could not parse OpenCode config ${file}: ${error.message}`)] };
  }
}

async function inspectOpenCode(projectRoot, env) {
  const user = userRoot("opencode", { env });
  const projectAgentRoot = path.join(projectRoot, ".opencode");
  const locations = [
    { scope: "user", root: user, agents: path.join(user, "agents"), configs: [path.join(user, "opencode.json")] },
    { scope: "project", root: projectAgentRoot, agents: path.join(projectAgentRoot, "agents"), configs: [path.join(projectRoot, "opencode.json"), path.join(projectAgentRoot, "opencode.json")] },
  ];
  const definitions = [];
  const settings = [];
  const findings = [];
  for (const location of locations) {
    const scan = await scanMarkdownAgents(location.agents, location.scope);
    definitions.push(...scan.definitions);
    findings.push(...scan.findings);
    for (const configPath of location.configs) {
      const config = await inspectOpenCodeConfig(configPath, location.scope);
      settings.push(...config.settings);
      findings.push(...config.findings);
    }
  }
  findings.push(...duplicateFindings([...definitions, ...settings]));
  for (const definition of [...definitions, ...settings]) {
    if (definition.model && !String(definition.model).includes("/")) {
      findings.push(finding("warning", "opencode-model-syntax", `OpenCode model ${definition.model} in ${definition.path} does not use provider/model syntax.`));
    }
  }
  if (definitions.length === 0 && settings.length === 0) findings.push(finding("information", "no-explicit-agents", "No OpenCode subagent model overrides were found."));
  return { host: "opencode", locations, definitions, settings, findings };
}

async function doctor(options) {
  const projectRoot = path.resolve(options.project ?? process.cwd());
  const hosts = normalizeDoctorHosts(options.host);
  const reports = [];
  for (const host of hosts) {
    if (host === "claude-code") reports.push(await inspectClaude(projectRoot, process.env));
    else if (host === "codex") reports.push(await inspectCodex(projectRoot, process.env));
    else reports.push(await inspectOpenCode(projectRoot, process.env));
  }
  const findings = reports.flatMap((report) => report.findings);
  const summary = {
    information: findings.filter((item) => item.level === "information").length,
    warnings: findings.filter((item) => item.level === "warning").length,
    errors: findings.filter((item) => item.level === "error").length,
  };
  const result = {
    command: "doctor",
    status: summary.errors > 0 ? "errors" : summary.warnings > 0 ? "warnings" : "healthy",
    projectRoot,
    hosts: reports,
    summary,
  };
  printResult(result, options.json);
  return summary.errors > 0 ? 1 : 0;
}

export async function main(argv = process.argv.slice(2)) {
  try {
    const { command, options } = parseArgs(argv);
    if (command === "help" || options.help) {
      process.stdout.write(usage());
      return 0;
    }
    if (command === "version") {
      process.stdout.write(`${PACKAGE_VERSION}\n`);
      return 0;
    }
    if (command === "configure") return await configure(options);
    if (command === "doctor") return await doctor(options);
    throw new CliError(`Unknown command: ${command}`);
  } catch (error) {
    if (error instanceof CliError) {
      process.stderr.write(`sew-models: ${error.message}\n`);
      return error.exitCode;
    }
    process.stderr.write(`sew-models: unexpected error: ${error.stack ?? error.message}\n`);
    return 1;
  }
}

const direct = process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url;
if (direct) process.exitCode = await main();

export const internals = Object.freeze({
  HOSTS,
  ROLES,
  PRESETS,
  MARKER,
  parseArgs,
  normalizePreset,
  parseRoleMap,
  homeDirectory,
  userRoot,
  projectRootForHost,
  resolveTargetRoot,
  managedPath,
  stripFrontmatter,
  parseFrontmatterScalars,
  parseTomlScalars,
  parseJsonc,
  renderAlias,
  isManagedContent,
  isContained,
  inspectClaude,
  inspectCodex,
  inspectOpenCode,
});
